create table if not exists public.inventory (
  id bigint generated by default as identity primary key,
  item_code text,
  name text not null,
  brand text,
  category text,
  size text,
  cost numeric default 0,
  list_price numeric default 0,
  actual_sale_price numeric,
  expected_profit numeric,
  actual_profit numeric,
  location text,
  notes text,
  image_path text,
  status text default '在庫中',
  created_at text,
  sold_date text,
  sold_channel text,
  return_flag integer default 0
);

alter table public.inventory enable row level security;

create policy "inventory read"
on public.inventory
for select
using (true);

create policy "inventory insert"
on public.inventory
for insert
with check (true);

create policy "inventory update"
on public.inventory
for update
using (true)
with check (true);

create policy "inventory delete"
on public.inventory
for delete
using (true);
